In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from services.manager_variables_excel_datos_doris import *

In [8]:
df = get_df_datos_doris()
df_filtrado = filtrar_df_datos_doris_por_orden_de_servicio(df)

c:\programacion\codigos_python\drift_buoys\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [14]:
df.tail(11)

,serial_de_sonda,OS,mes_vigencia,serial_original,serial_UABC,fecha_y_hora_de_despliegue_campo,fecha_y_hora_de_la_primera_transmision_campo,latitud_de_despliegue_campo,longitud_de_despliegue_campo,tirante_de_despligue_campo,...,longitud_maniobra,fecha_y_hora_de_despliegue_plan,latitud_plan,longitud_plan,fecha_y_hora_de_ultima_medicion,buoy_id,FechaInicial Local,FechaFinal Local,hora_de_la_ultima_fila_eliminada,aux_para_nombres_de_sensores
28,9878221,202,NaN,4878221,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,NaN,2026-04-18 17:59:00,19.354231,-92.134043,NaN,NaN,2026-03-26 12:01:00,2026-03-26 12:01:00,NaN,S28
29,9878504,202,NaN,4878504,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.140274,2026-04-18 18:01:00,19.358000,-92.140000,NaN,NaN,2026-03-26 12:03:00,NaN,NaN,S29
30,9878225,202,NaN,4878225,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.148471,2026-04-18 18:12:00,19.365000,-92.148000,NaN,NaN,2026-03-26 12:14:00,NaN,NaN,S30
31,9876178,202,NaN,4876178,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.239752,2026-04-18 18:22:00,19.502000,-92.239000,NaN,NaN,2026-03-26 12:24:00,NaN,NaN,S31
32,9878203,202,NaN,4878203,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.250652,2026-04-18 18:59:00,19.531000,-92.250000,NaN,NaN,2026-03-26 13:01:00,NaN,NaN,S32
33,9878218,202,NaN,4878218,NaN,NaT,NaT,NaN,NaN,NaN,...,-93.326375,2026-04-26 18:23:00,18.727000,-93.326000,NaN,NaN,NaT,NaN,NaN,S34
34,4878505,202,NaN,4878505,NaN,NaT,NaT,NaN,NaN,NaN,...,-93.266575,2026-04-26 17:02:00,18.801000,-93.266000,NaN,NaN,NaT,NaN,NaN,S33

In [16]:
df_filtrado.head(10)

,serial_de_sonda,OS,mes_vigencia,serial_original,serial_UABC,fecha_y_hora_de_despliegue_campo,fecha_y_hora_de_la_primera_transmision_campo,latitud_de_despliegue_campo,longitud_de_despliegue_campo,tirante_de_despligue_campo,...,longitud_maniobra,fecha_y_hora_de_despliegue_plan,latitud_plan,longitud_plan,fecha_y_hora_de_ultima_medicion,buoy_id,FechaInicial Local,FechaFinal Local,hora_de_la_ultima_fila_eliminada,aux_para_nombres_de_sensores
28,9878221,202,NaN,4878221,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,NaN,2026-04-18 17:59:00,19.354231,-92.134043,NaN,NaN,2026-03-26 12:01:00,2026-03-26 12:01:00,NaN,S28
29,9878504,202,NaN,4878504,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.140274,2026-04-18 18:01:00,19.358000,-92.140000,NaN,NaN,2026-03-26 12:03:00,NaN,NaN,S29
30,9878225,202,NaN,4878225,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.148471,2026-04-18 18:12:00,19.365000,-92.148000,NaN,NaN,2026-03-26 12:14:00,NaN,NaN,S30
31,9876178,202,NaN,4876178,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.239752,2026-04-18 18:22:00,19.502000,-92.239000,NaN,NaN,2026-03-26 12:24:00,NaN,NaN,S31
32,9878203,202,NaN,4878203,NaN,2026-04-19 18:00:00,2026-04-19 18:00:00,NaN,NaN,NaN,...,-92.250652,2026-04-18 18:59:00,19.531000,-92.250000,NaN,NaN,2026-03-26 13:01:00,NaN,NaN,S32
33,9878218,202,NaN,4878218,NaN,NaT,NaT,NaN,NaN,NaN,...,-93.326375,2026-04-26 18:23:00,18.727000,-93.326000,NaN,NaN,NaT,NaN,NaN,S34
34,4878505,202,NaN,4878505,NaN,NaT,NaT,NaN,NaN,NaN,...,-93.266575,2026-04-26 17:02:00,18.801000,-93.266000,NaN,NaN,NaT,NaN,NaN,S33

In [18]:
latitudes = get_latitudes(df_filtrado)
latitudes

[nan, 19.358039, 19.365968, 19.50246, 19.531374, 18.727398, 18.8015922]

In [19]:
longitudes = get_longitudes(df_filtrado)
longitudes

[nan, -92.140274, -92.148471, -92.239752, -92.250652, -93.326375, -93.266575]